'use client';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Card} from '@/components/ui/card';
import {Save,Plus,Trash2,RefreshCw} from 'lucide-react';
import {contentSchema,type SiteContent} from '@/lib/site-content';
type Initial={content:SiteContent;revision:number;updatedAt:string|null};
function Field({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <label className="editor-field"><span>{label}</span>{multiline?<Textarea value={value} onChange={e=>onChange(e.target.value)} rows={4}/>:<Input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
export default function Editor({initial}:{initial:Initial}){
 const [draft,setDraft]=useState(initial.content),[saved,setSaved]=useState(initial.content),[revision,setRevision]=useState(initial.revision),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
 const dirty=JSON.stringify(draft)!==JSON.stringify(saved);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return ()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 function field(key:keyof SiteContent,value:string){setDraft(d=>({...d,[key]:value}))}
 function leader(i:number,key:string,value:string){setDraft(d=>({...d,leaders:d.leaders.map((l,j)=>j===i?{...l,[key]:value}:l)}))}
 function report(i:number,key:string,value:unknown){setDraft(d=>({...d,reports:d.reports.map((r,j)=>j===i?{...r,[key]:value}:r)}))}
 async function save(){setError(false);const parsed=contentSchema.safeParse(draft);if(!parsed.success){setError(true);setMessage(parsed.error.issues.map(e=>`${e.path.join(' → ')}: ${e.message}`).join('\n'));return}setSaving(true);setMessage('Saving changes…');try{const response=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json','X-MTHS-Editor':'1'},body:JSON.stringify({content:parsed.data,revision})});const data=await response.json() as {error?:string;revision:number};if(!response.ok)throw Error(data.error||'Save failed.');setSaved(parsed.data);setRevision(data.revision);setMessage('Saved. Your changes are now on the website.')}catch(e){setError(true);setMessage(e instanceof Error?e.message:'Save failed. Please try again.')}finally{setSaving(false)}}
 return <main className="editor-shell"><header className="editor-header"><div><a href="/" target="_blank" rel="noreferrer" className="text-link">View website</a><h1>Website editor</h1><p>Update your club’s content. Save when you’re ready for the changes to appear.</p></div><div className="editor-save"><span>{dirty?'Unsaved changes':'All changes saved'}</span><Button disabled={saving||!dirty} aria-busy={saving} onClick={save}>{saving?<RefreshCw className="animate-spin"/>:<Save/>}{saving?'Saving…':'Save changes'}</Button></div></header>{message&&<div role={error?'alert':'status'} className={'editor-message '+(error?'editor-error':'')}>{message}</div>}<fieldset disabled={saving} className="min-w-0"><Tabs defaultValue="home"><TabsList className="editor-tabs"><TabsTrigger value="home">Homepage</TabsTrigger><TabsTrigger value="leadership">Leadership</TabsTrigger><TabsTrigger value="research">Research</TabsTrigger><TabsTrigger value="portfolio">Portfolio feed</TabsTrigger></TabsList>
 <TabsContent value="home"><Card className="editor-card"><h2>Homepage text</h2><div className="editor-grid">{([['heroEyebrow','Small heading'],['heroTitle','Main headline (one line per row)'],['heroSubtitle','Subtitle'],['heroNote','Short statement'],['missionTitle','Mission heading'],['missionIntro','Mission opening paragraph'],['missionBody','Mission main paragraph'],['homeResearchNote','Research note below cards']] as const).map(([key,label])=><Field key={key} label={label} value={draft[key]} multiline={key!=='heroEyebrow'&&key!=='heroNote'} onChange={v=>field(key,v)}/>)}</div></Card></TabsContent>
 <TabsContent value="leadership"><Card className="editor-card"><h2>Leadership</h2><Field label="Roster notice (leave blank to hide)" multiline value={draft.leadershipNotice} onChange={v=>field('leadershipNotice',v)}/><p>Use public HTTPS image links for photos. Leave contact fields blank if you do not want them displayed.</p></Card>{draft.leaders.map((l,i)=><Card className="editor-card" key={i}><div className="editor-row"><h2>{l.name||'New member'} <small>· {l.role}</small></h2><Button variant="ghost" onClick={()=>setDraft(d=>({...d,leaders:d.leaders.filter((_,j)=>j!==i)}))}><Trash2/>Remove member</Button></div><div className="editor-grid">{(['name','role','bio','photo','email','linkedin'] as const).map(key=><Field key={key} label={{name:'Name',role:'Role',bio:'Biography',photo:'Photo URL',email:'Contact email',linkedin:'LinkedIn URL'}[key]} value={l[key]} multiline={key==='bio'} onChange={v=>leader(i,key,v)}/>)}</div></Card>)}<Button variant="outline" onClick={()=>setDraft(d=>({...d,leaders:[...d.leaders,{name:'New member',role:'Role',bio:'',photo:'',email:'',linkedin:''}]}))}><Plus/>Add member</Button></TabsContent>
 <TabsContent value="research"><Card className="editor-card"><h2>Research library</h2><Field label="Library notice (leave blank to hide)" multiline value={draft.researchNotice} onChange={v=>field('researchNotice',v)}/><p>Add a publicly accessible PDF or report link. Documents stay at the link you provide.</p></Card>{draft.reports.map((r,i)=><Card className="editor-card" key={r.id}><div className="editor-row"><h2>{r.title||'New report'}</h2><Button variant="ghost" onClick={()=>setDraft(d=>({...d,reports:d.reports.filter((_,j)=>j!==i)}))}><Trash2/>Remove report</Button></div><div className="editor-grid">{(['title','ticker','type','sector','description','pdfUrl'] as const).map(key=><Field key={key} label={{title:'Title',ticker:'Ticker / short label',type:'Report type',sector:'Sector',description:'Summary',pdfUrl:'PDF or report URL'}[key]} value={r[key]} multiline={key==='description'} onChange={v=>report(i,key,v)}/>)}<label className="editor-field"><span>Status</span><Select value={r.status} onValueChange={v=>report(i,'status',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Long','Short','Watchlist','Executed'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label><label className="flex gap-3 items-center"><Checkbox checked={r.sample} onCheckedChange={v=>report(i,'sample',v===true)}/>Label as sample material</label></div><h3>Report sections</h3>{r.sections.map(([heading,body],j)=><div className="editor-section" key={j}><Field label="Section heading" value={heading} onChange={v=>report(i,'sections',r.sections.map((s,k)=>k===j?[v,s[1]]:s))}/><Field label="Section text" multiline value={body} onChange={v=>report(i,'sections',r.sections.map((s,k)=>k===j?[s[0],v]:s))}/><Button variant="ghost" onClick={()=>report(i,'sections',r.sections.filter((_,k)=>k!==j))}>Remove section</Button></div>)}<Button variant="outline" onClick={()=>report(i,'sections',[...r.sections,['New section','']])}><Plus/>Add section</Button></Card>)}<Button variant="outline" onClick={()=>setDraft(d=>({...d,reports:[...d.reports,{id:crypto.randomUUID(),title:'New report',ticker:'',type:'Investment memo',sector:'',status:'Watchlist',description:'',pdfUrl:'',sample:false,sections:[]}]}))}><Plus/>Add report</Button></TabsContent>
 <TabsContent value="portfolio"><Card className="editor-card"><h2>Shared portfolio connection</h2><p>This published Google Sheets CSV link becomes the default for all visitors. Leave it blank to use the sample portfolio. A visitor’s browser-specific connection takes priority.</p><Field label="Published Holdings CSV URL" value={draft.sheetUrl} onChange={v=>field('sheetUrl',v)}/><p>Required headers: Ticker, Company Name, Sector, Shares, Cost Basis, Current Price. Add Cash Balance when tracking closed trades. Publish only data you want site visitors to see.</p></Card></TabsContent>
 </Tabs></fieldset><p className="editor-footnote">Removals take effect only after saving. Reload before saving to discard unsaved edits.</p></main>
}
